### ISSUE TITLE
Is there any way to disable SublimeTmpl from adding keymap?

### ISSUE THREAD

**Issue by leesei** [kairyou/SublimeTmpl#10]
SublimeTmpl overrides several of the keymaps that I use, is there a setting to disable SublimeTmpl  keymap?
I know I can override them in my user keymap file but that is extra work, I only need the default settings.

**Comment by kairyou** [comment]
Hi, I have added a new version 1.1.1.
Please try `disabled_keymap_actions`options.
https://github.com/kairyou/SublimeTmpl#default-key-bindings

**Comment by leesei** [comment]
Thanks a lot, it saved my day :satisfied:.
I hope other packages have this options too.

**Comment by kairyou** [comment]
:smiley: I'm glad it helped.
Maybe you can suggest other package authors use the [on_query_context API](http://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.EventListener).
