### ISSUE TITLE
Where is the default Key Bindings ?

### ISSUE THREAD

**Issue by zangree** [kairyou/SublimeTmpl#11]
It's an excellent sublime plug-in component. But I'm new, when I learn the code, I can't find the default Key Bindings, for example ''ctrl+alt+c:css", so where are those?

**Comment by kairyou** [comment]
Hi, 

By default, packages will be installed by placing a .sublime-package file (zip archive).

You can download the default [key map](https://github.com/kairyou/SublimeTmpl/blob/master/Default.sublime-keymap), and put it in the
`"$HOME/Library/Application Support/Sublime Text 3/Packages/SublimeTmpl/"` folder.

Or, [git clone this package](https://github.com/kairyou/SublimeTmpl#installation).

**Comment by zangree** [comment]
Thanks！
