### ISSUE TITLE
Why does it show the CR ?

### ISSUE THREAD

**Issue by jiyiren** [kairyou/SublimeTmpl#12]
I install it in Sublime Text3 Build 3083 by git clone the url and it works.However,when I create a html template,it shows that:
![](http://7xknpe.com1.z0.glb.clouddn.com/sublimet3st3.png)
I save it named hah.html.
And then I close the file,I opened it again,it shows that:
![](http://7xknpe.com1.z0.glb.clouddn.com/sublimet3st3close.png)

**Please fix the problem!!**

**Comment by kairyou** [comment]
Hi,

I have tested this package in Sublime Text3 Build 3103, it works normally.

One possible reason is that the `git` will convert LF to CRLF when checking out text files (Maybe, it is enabled by default on Windows).

You can try disable `autocrlf`  via the Git Bash:
`git config --global core.autocrlf false`
and  try to clone this repo again.

Or, download the source in ZIP format from GitHub, and unzip it to "Packages" directory. (The folder name should be `SublimeTmpl`)

**Comment by shadowii** [comment]
I'm actually getting the same problem on Build 3103 Windows, but my template files are not source controlled.

**Comment by shadowii** [comment]
I found a workaround for my scenario. I changed the line ending type for my custom template to Unix, then saved it. Creating a new file based on that template with Windows line endings then works properly with no CRs.

**Comment by kairyou** [comment]
Thanks to both of you.
This has been fixed in version 1.1.2.
