### ISSUE TITLE
Custom templates gets ignored

### ISSUE THREAD

**Issue by oefterdal** [kairyou/SublimeTmpl#13]
I have created a custom template, but when I create a new file from that template the files is blank. 
The template is stored in User/SublimeTmpl/template as blogpost.tmpl

I also added a new item to the MENU as: 
          {
                        "caption": "BLOG POST",
                        "command": "sublime_tmpl",
                        "args": {
                            "type": "blogpost"
                        }

**Comment by kairyou** [comment]
Hi, 

I have try created `blogpost.tmpl` in `Packages/User/SublimeTmpl/templates/`, and added the item in menu. It works normally.
![image](https://cloud.githubusercontent.com/assets/544524/13032382/6102afd4-d32b-11e5-81ad-ad7315108381.png)
![image](https://cloud.githubusercontent.com/assets/544524/13032398/d2e98258-d32b-11e5-9262-04b3ff0ac7df.png)

**Comment by oefterdal** [comment]
I had a isse with an variable, working now. Thank you.
