### ISSUE TITLE
support ${file name}, ${project name} variables

### ISSUE THREAD

**Issue by xuanliu-aa** [kairyou/SublimeTmpl#14]
Good plugin, but I found that ${file name}, ${project name} is missing. Is it possible?

**Comment by kairyou** [comment]
- The `file_name` is empty when creating new file. And, it doesn't make any sense to get the file name of the current active tab.
- The variables `project_path`, `platform` and `project_base_name` can be added to SublimeTmpl, but those variables will work only in sublime text 3. There is no API to get project info in ST2.

**Comment by xuanliu-aa** [comment]
take consideration for below template:

//
//  AccountManager.h
//  Generator
//
//  Created by Andrew on 6/12/15.
//  Copyright (c) 2015 Google. All rights reserved.

**Comment by kairyou** [comment]
Yep, I know, and it would be a good feature.
1. ${file_name} is only available after the new file has been saved. And, It's null value when creating new file.
2. As I said earlier, ${project name} can be supported, but it only works in ST version 3.

**Comment by xuanliu-aa** [comment]
yes I am using 3:)

**Comment by kairyou** [comment]
Done, please see the [README.md@4075770](/kairyou/SublimeTmpl/commit/4075770/README.md?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8), and update SublimeTmpl to version 1.1.4.
