### ISSUE TITLE
How to prevent this plugin from updating itself?

### ISSUE THREAD

**Issue by vrbvillor** [kairyou/SublimeTmpl#15]
I've edited the content of this plugin, but it updates everyday, so I have to paste the content edited to cover the new script of this plugin. How to prevent the plugin from  auto-updating?

**Comment by kairyou** [comment]
hello,
你是国人吧, 自动更新是packagecontrol的功能, 可以配置它的[auto_upgrade_ignore](https://packagecontrol.io/docs/settings)选项.
另外, 如果你修改的不是Python文件本身, 而是User目录的setting或者tmpl, 插件升级是不会有任何影响的.
另外, updates everyday 有些夸张~, 没人提Issues活PR, 插件是不会频繁更新了.

**Comment by vrbvillor** [comment]
话说，下边没有user目录啊，只有一个templates目录。的确是每天更新，我每天都得把之前改的东西覆盖过来……

**Comment by kairyou** [comment]
Sublime / Preferences / Package Settings / SublimeTmpl / Settings - User
这个就是自定义配置, 配置后, 会覆盖插件目录的默认配置, 目录是/Packages/User
自定义模板: /Packages/User/SublimeTmpl

**Comment by vrbvillor** [comment]
可是我改的是菜单跟快捷键啊，那两个不是在user里边的啊。还是说我把整个SublimeTmpl目录，都粘到Users里边？

**Comment by kairyou** [comment]
![image](https://cloud.githubusercontent.com/assets/544524/17045956/eab9325a-5000-11e6-8ed9-452b946de754.png)
配置菜单, Key Bindings - user 增加配置可以覆盖默认的快捷键.
umm... 你是增加了其他语法对吧?  然后希望在菜单 显示这个语法?
支持user菜单的功能, 看来必须要更新个新版本解决了, 哈~

**Comment by kairyou** [comment]
准备新版本, 增加user menu, 比如这样:
![image](https://cloud.githubusercontent.com/assets/544524/17047297/ef00f358-500e-11e6-94b9-f72d9770aec8.png)
