### ISSUE TITLE
是否可以像模板引擎一样变量自定义？

### ISSUE THREAD

**Issue by chenquincy** [kairyou/SublimeTmpl#17]
我想新建一个vue模板，根据文件名给其添加类名，比如MyFile.vue添加类名my-file
在webstorm模板引擎中我是这么写的
#set($lowerName = $NAME.replaceAll("([a-zA-Z](?=[A-Z]))", "$1-").toLowerCase())
<template>
  <div class="$lowerName">
  </div>
</template>

<script>
export default {
  name: '${NAME}',
  data () {
    return {}
  }
}
</script>

<style lang="scss" rel="stylesheet/scss" scoped>
  .$lowerName {
    
  }
</style>

那么在sublime中能否做到，可以的话怎么做呢？

**Comment by kairyou** [comment]
不行, 变量只能预设, 根据保存后的文件名, sublime不行了.

**Comment by chenquincy** [comment]
好吧   那只能手动来了   谢谢
