### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by vulkanosaure** [kairyou/SublimeTmpl#18]
this is not an issue, just my idea about this plugin. I think to be truly interesting, it should handle file creation and naming too, appearing on the menu after a right click on a specific folder. 
Because right now, i don't really file any advantage to use this, rather than hit ctrl+N and launch a snippet.

Best regards

**Comment by kairyou** [comment]
Hi,

![image](https://cloud.githubusercontent.com/assets/544524/25836656/3a22c55a-34bb-11e7-8409-a81d1a8d689e.png)
I have added a new version 1.1.6.
Thanks
