### ISSUE TITLE
在模板中添加script标签包含js代码自定义的模板就会有问题

### ISSUE THREAD

**Issue by zhouy4810** [kairyou/SublimeTmpl#19]
在html模板中添加如下代码创建的文件就变为空了：
<script>
    $(function(){
        $("img.lazy").lazyload({
            threshold : 200
        });
        //本专题页点击多规格跳转到产品详情页
        $('.desc').on('click', function(event){
            event.preventDefault();
            findParent(this, 'item').find('.godetail').click();
        });
        function findParent(obj, str){
            var $obj = $(obj);
            while(!$obj.hasClass(str)){
                $obj = $obj.parent();
            }
            return $obj;
        }
    });
</script>

**Comment by zhouy4810** [comment]
好吧，我找到原因了，是因为jQuery的$和你的变量前缀$想冲突了。

**Comment by kairyou** [comment]
是的, $是Sublime snippet的关键词, 你可以用`\$`来转义. 如:
```
<script>
    \$(function(){ \$("img.lazy").lazyload({ threshold : 200 });
    // \$('.desc').on('click', function(event){ event.preventDefault(); findParent(this, 'item').find('.godetail').click(); }); function findParent(obj, str){ var \$obj = \$(obj); while(!\$obj.hasClass(str)){ \$obj = \$obj.parent(); } return \$obj; } });
</script>
```
