### ISSUE TITLE
这个插件能做到实时更新么 

### ISSUE THREAD

**Issue by yuedingwangji** [kairyou/SublimeTmpl#26]
举个例子，我公司，和家里的电脑同事打开了 ST，公司的电脑在编辑印象笔记的一个笔记本，编辑完后更新上去了， 家里的电脑没做任何操作， 如何这时候，家里的电脑更新 ， 就会覆盖公司的更新，
这个时候我要看最新的数据，每次都只能重新打开笔记本，有什么办法能让家里的电脑不用重新打开笔记本，向刷新网页一样去获取公司电脑更新的最新内容么？  因为有时新开了一个笔记本，那边还有一个窗口，开着个旧的笔记本，如果不小心在开着旧笔记本的窗口按了更新，那就GG了

**Comment by kairyou** [comment]
你的想法不错, 不过, 这不在这个插件的功能范围了. 当: 新建-保存后, 和这个插件已经没有任何关系了, 插件的作用是模板而已.
实时更新, 估计要 印象笔记 出个插件, 配置用户/名密码 或 token 之类的, 定时同步.
