### ISSUE TITLE
保存文件名可以去掉后缀么？

### ISSUE THREAD

**Issue by justpsvm** [kairyou/SublimeTmpl#27]
```json
"enable_file_variables_on_save": true
```

在开启上面的状态时 保存文件会把后缀带进去 可以只带入文件名吗？ 不要后缀

**Comment by kairyou** [comment]
Hi, 一般来说, 文件名带后缀是比较常见的做法. 暂时不会做这个功能.
如果以后如果有类似需求的人多, 会增加1个额外的变量.
